name: Generate update.xml for AutoUpdater.NET

on:
  release:
    types: [published]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set version and filename from tag
        id: vars
        run: |
          RAW_VERSION="${GITHUB_REF##*/}"         
          CLEAN_VERSION="${RAW_VERSION#v}"       
          CLEAN_VERSION="${CLEAN_VERSION#V}"
          echo "VERSION=$CLEAN_VERSION" >> $GITHUB_ENV
          echo "FILENAME=FinanzAppSetup.exe" >> $GITHUB_ENV

      - name: Create update.xml
        run: |
          echo "<item>" > update.xml
          echo "  <version>${{ env.VERSION }}</version>" >> update.xml
          echo "  <url>https://github.com/${{ github.repository }}/releases/download/v${{ env.VERSION }}/${{ env.FILENAME }}</url>" >> update.xml
          echo "  <mandatory>false</mandatory>" >> update.xml
          echo "</item>" >> update.xml

      - name: Push update.xml to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          force_orphan: true


